### ISSUE TITLE
Sensor no longer appearing in HA

### ISSUE THREAD

**Issue by juan11perez** [edekeijzer/osrm_travel_time#2]
The sensor is no longer appearing in HA.

Local osrm server is running (docker) without error. sensor is just not available.

I was wondering if still working for others?

**Comment by edekeijzer** [comment]
I have just recently restored my OSRM servers, but I see the sensors are no longer in my own environment. I'll have a look into it.

**Comment by juan11perez** [comment]
Thank  you

**Comment by juan11perez** [comment]
Good day,  did you had a chance to look into this? Thank you

**Comment by L0rdShrek** [comment]
In my logs there is an error with the following message:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/osrm_travel_time/sensor.py", line 141, in async_setup_platform
    units = config.get(CONF_UNIT_SYSTEM, hass.config.units.name)
                                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UnitSystem' object has no attribute 'name'
```
